version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init.sh:/docker-entrypoint-initdb.d/mysql-init.sh
    networks:
      - app-network

  python-app:
    build: .
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: "${MYSQL_DATABASE}"
      DB_USER: "root"
      DB_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

networks:
  app-network:
    driver: bridge
