version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"  # Using environment variables
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - "3306:3306"
    networks:
      - app-network

  python-app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: "${MYSQL_DATABASE}"
      DB_PASSWORD: "${MYSQL_ROOT_PASSWORD}"  # Avoiding hardcoded passwords

networks:
  app-network:
    driver: bridge
